'use strict';

require('dotenv').config();
const express = require('express');
const axios = require('axios');
const BoxSDK = require('box-node-sdk');
const { AssemblyAI } = require('assemblyai');
const { spawn, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const app = express();
app.use(express.json());

// Tracks files currently being processed, so duplicate webhook deliveries for
// the same upload don't kick off a second transcription in parallel.
const inFlight = new Set();

const VIDEO_EXTENSIONS = new Set(['mp4', 'mov', 'avi', 'mkv']);
const BOX_COMMENT_LIMIT = 9000;

// Files over this size skip the direct-URL path and go through ffmpeg audio extraction.
// AssemblyAI's file size limit is 5 GB; we use 2 GB to stay well clear of it.
const FFMPEG_THRESHOLD_BYTES = 2 * 1024 * 1024 * 1024;

// Find ffmpeg: FFMPEG_PATH env var, local folder, system PATH, then ffmpeg-static.
function findFfmpeg() {
  if (process.env.FFMPEG_PATH && fs.existsSync(process.env.FFMPEG_PATH))
    return process.env.FFMPEG_PATH;
  const local = path.join(__dirname, 'ffmpeg.exe');
  if (fs.existsSync(local)) return local;
  try {
    const cmd = process.platform === 'win32' ? 'where ffmpeg' : 'which ffmpeg';
    return execSync(cmd, { stdio: ['pipe','pipe','pipe'] }).toString().trim().split('\n')[0];
  } catch {}
  try { return require('ffmpeg-static'); } catch {}
  return null;
}
const FFMPEG_PATH = findFfmpeg();

const aai = new AssemblyAI({ apiKey: process.env.ASSEMBLYAI_API_KEY });

// ─── Box JWT client ───────────────────────────────────────────────────────────

const BOX_CONFIG_PATH = path.join(__dirname, 'box_jwt_config.json');
let _boxSDK;
try {
  _boxSDK = BoxSDK.getPreconfiguredInstance(
    JSON.parse(fs.readFileSync(BOX_CONFIG_PATH, 'utf8'))
  );
} catch (err) {
  console.error(
    `FATAL: could not load Box config at ${BOX_CONFIG_PATH}\n` +
    `  ${err.message}\n` +
    `  Create it from box_jwt_config.example.json (Box Dev Console -> ` +
    `download the JWT config JSON) before starting the server.`
  );
  process.exit(1);
}
const boxClient = _boxSDK.getAppAuthClient('enterprise');

async function getBoxDownloadUrl(fileId) {
  return new Promise((resolve, reject) => {
    boxClient.files.getDownloadURL(fileId, null, (err, url) => {
      if (err) reject(err);
      else resolve(url);
    });
  });
}

async function postBoxComment(fileId, text) {
  return new Promise((resolve, reject) => {
    boxClient.comments.create(fileId, text, (err, comment) => {
      if (err) reject(err);
      else resolve(comment);
    });
  });
}

// ─── Comment chunker ──────────────────────────────────────────────────────────

function buildCommentChunks(transcriptText) {
  const baseHeader = 'Auto-Transcript\nGenerated by AssemblyAI\n\n';

  if ((baseHeader + transcriptText).length <= BOX_COMMENT_LIMIT) {
    return [baseHeader + transcriptText];
  }

  const chunks = [];
  let remaining = transcriptText;

  while (remaining.length > 0) {
    const partHeader = `Auto-Transcript (part ${chunks.length + 1})\nGenerated by AssemblyAI\n\n`;
    const available = BOX_COMMENT_LIMIT - partHeader.length;

    if (remaining.length <= available) {
      chunks.push(partHeader + remaining);
      break;
    }

    let cutAt = available;
    const dot = remaining.lastIndexOf('. ', cutAt);
    if (dot > available * 0.6) {
      cutAt = dot + 2;
    } else {
      const space = remaining.lastIndexOf(' ', cutAt);
      if (space > 0) cutAt = space;
    }

    chunks.push(partHeader + remaining.substring(0, cutAt).trimEnd());
    remaining = remaining.substring(cutAt).trimStart();
  }

  return chunks.map((chunk, i) =>
    chunk.replace(`(part ${i + 1})`, `(part ${i + 1} of ${chunks.length})`)
  );
}

// ─── ffmpeg audio extraction ──────────────────────────────────────────────────
// Reads the video directly from the Box pre-signed URL — no full download needed.
// Outputs a mono MP3 at 64kbps (plenty for speech; keeps the temp file small).
// Returns the path to the temp file; caller is responsible for deleting it.

function extractAudio(downloadUrl, tag) {
  const tempPath = path.join(os.tmpdir(), `bt_audio_${Date.now()}.mp3`);
  console.log(`${tag} Extracting audio via ffmpeg -> ${path.basename(tempPath)}`);

  return new Promise((resolve, reject) => {
    const proc = spawn(FFMPEG_PATH, [
      '-i', downloadUrl,
      '-vn',                // strip video stream
      '-acodec', 'libmp3lame',
      '-ac', '1',           // mono — sufficient for speech transcription
      '-ab', '64k',         // 64 kbps — a 1-hour file becomes ~28 MB
      '-y',                 // overwrite if temp file already exists
      tempPath,
    ]);

    proc.stderr.on('data', () => {}); // ffmpeg progress goes to stderr; suppress it

    proc.on('close', code => {
      if (code === 0) {
        const sizeMB = (fs.statSync(tempPath).size / 1024 / 1024).toFixed(1);
        console.log(`${tag} Audio extracted: ${sizeMB} MB`);
        resolve(tempPath);
      } else {
        reject(new Error(`ffmpeg exited with code ${code}`));
      }
    });

    proc.on('error', err => reject(new Error(`ffmpeg not found: ${err.message}`)));
  });
}

// ─── AssemblyAI transcription ─────────────────────────────────────────────────

function handleTranscriptResult(transcript) {
  if (transcript.status === 'error') {
    if (transcript.error && transcript.error.includes('no spoken audio')) return null;
    throw new Error(`AssemblyAI error: ${transcript.error}`);
  }
  return transcript.text;
}

// Small/medium files: pass the Box URL directly — AssemblyAI fetches the file itself.
async function transcribeUrl(downloadUrl, tag) {
  console.log(`${tag} Sending to AssemblyAI (direct URL)...`);
  const transcript = await aai.transcripts.transcribe({
    audio_url: downloadUrl,
    speech_models: ['universal-2'],
  });
  return handleTranscriptResult(transcript);
}

// Large files: upload the ffmpeg-extracted audio file, then transcribe.
async function transcribeAudioFile(filePath, tag) {
  console.log(`${tag} Uploading extracted audio to AssemblyAI...`);
  const buffer = fs.readFileSync(filePath);
  const uploadUrl = await aai.files.upload(buffer);
  console.log(`${tag} Transcription started — waiting for result...`);
  const transcript = await aai.transcripts.transcribe({
    audio_url: uploadUrl,
    speech_models: ['universal-2'],
  });
  return handleTranscriptResult(transcript);
}

// ─── Core pipeline ────────────────────────────────────────────────────────────

async function processFile(fileId, fileName, fileSize) {
  const tag = `[${fileName}]`;
  try {
    console.log(`${tag} Getting Box download URL...`);
    const downloadUrl = await getBoxDownloadUrl(fileId);

    let transcriptText;

    if (fileSize > FFMPEG_THRESHOLD_BYTES) {
      const sizeGB = (fileSize / 1024 / 1024 / 1024).toFixed(1);
      console.log(`${tag} Large file (${sizeGB} GB) — extracting audio first...`);
      let audioPath;
      try {
        audioPath = await extractAudio(downloadUrl, tag);
        transcriptText = await transcribeAudioFile(audioPath, tag);
      } finally {
        if (audioPath && fs.existsSync(audioPath)) {
          fs.unlinkSync(audioPath);
          console.log(`${tag} Temp audio file removed.`);
        }
      }
    } else {
      console.log(`${tag} Transcription started — waiting for result...`);
      transcriptText = await transcribeUrl(downloadUrl, tag);
    }

    if (!transcriptText) {
      console.log(`${tag} No spoken audio detected, skipping comment.`);
      return;
    }
    console.log(`${tag} Transcript ready (${transcriptText.length} chars)`);

    const chunks = buildCommentChunks(transcriptText);
    console.log(`${tag} Posting ${chunks.length} comment(s) to Box...`);
    for (const chunk of chunks) {
      await postBoxComment(fileId, chunk);
    }
    console.log(`${tag} Done.`);
  } catch (err) {
    console.error(`${tag} Pipeline failed: ${err.message}`);
  }
}

// ─── Webhook endpoint ─────────────────────────────────────────────────────────

app.post('/webhook', (req, res) => {
  res.sendStatus(200);

  const { trigger, source } = req.body || {};

  if (!source || source.type !== 'file') {
    console.log('Webhook received: no file source, skipping.');
    return;
  }

  const fileId = source.id;
  const fileName = source.name || '';
  const fileSize = source.size || 0;
  const ext = (fileName.split('.').pop() || '').toLowerCase();
  const sizeMB = (fileSize / 1024 / 1024).toFixed(1);

  console.log(`Webhook: ${trigger} -> "${fileName}" (${sizeMB} MB, ID: ${fileId})`);

  if (!VIDEO_EXTENSIONS.has(ext)) {
    console.log(`Skipping non-video file (.${ext})`);
    return;
  }

  // Box may deliver the same webhook more than once (at-least-once delivery).
  // Guard against processing a file twice concurrently; the transcript-comment
  // check in processFile handles dedup across restarts.
  if (inFlight.has(fileId)) {
    console.log(`Already processing ${fileId}, ignoring duplicate webhook.`);
    return;
  }
  inFlight.add(fileId);
  Promise.resolve(processFile(fileId, fileName, fileSize)).finally(() =>
    inFlight.delete(fileId)
  );
});

// ─── Start ────────────────────────────────────────────────────────────────────

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Marketing Video Transcriber running on port ${PORT}`);
  console.log(`ffmpeg path: ${FFMPEG_PATH}`);
  console.log(`Large file threshold: ${(FFMPEG_THRESHOLD_BYTES / 1024 / 1024 / 1024).toFixed(0)} GB`);
});
