'use strict';

// Manual pipeline trigger — run this any time to process a specific Box file:
//   node trigger.js <fileId>
//   node trigger.js <fileId> <fileName>   (optional, for cleaner logs)

require('dotenv').config();
const axios = require('axios');
const { AssemblyAI } = require('assemblyai');
const { spawn, execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const BOX_API = 'https://api.box.com/2.0';
const BOX_COMMENT_LIMIT = 9000;
const FFMPEG_THRESHOLD_BYTES = 2 * 1024 * 1024 * 1024;

// Find ffmpeg: FFMPEG_PATH env var, local folder, system PATH, then ffmpeg-static.
function findFfmpeg() {
  if (process.env.FFMPEG_PATH && fs.existsSync(process.env.FFMPEG_PATH))
    return process.env.FFMPEG_PATH;
  const local = path.join(__dirname, 'ffmpeg.exe');
  if (fs.existsSync(local)) return local;
  try {
    const cmd = process.platform === 'win32' ? 'where ffmpeg' : 'which ffmpeg';
    return execSync(cmd, { stdio: ['pipe','pipe','pipe'] }).toString().trim().split('\n')[0];
  } catch {}
  try { return require('ffmpeg-static'); } catch {}
  return null;
}
const FFMPEG_PATH = findFfmpeg();

const aai = new AssemblyAI({ apiKey: process.env.ASSEMBLYAI_API_KEY });

function boxHeaders() {
  return { Authorization: `Bearer ${process.env.BOX_DEVELOPER_TOKEN}` };
}

async function getBoxDownloadUrl(fileId) {
  const res = await axios.get(`${BOX_API}/files/${fileId}/content`, {
    headers: boxHeaders(), maxRedirects: 0, validateStatus: s => s === 302,
  });
  return res.headers.location;
}

async function postBoxComment(fileId, text) {
  await axios.post(
    `${BOX_API}/comments`,
    { message: text, item: { type: 'file', id: fileId } },
    { headers: { ...boxHeaders(), 'Content-Type': 'application/json' } }
  );
}

function buildCommentChunks(transcriptText) {
  const baseHeader = 'Auto-Transcript\nGenerated by AssemblyAI\n\n';
  if ((baseHeader + transcriptText).length <= BOX_COMMENT_LIMIT) return [baseHeader + transcriptText];
  const chunks = [];
  let remaining = transcriptText;
  while (remaining.length > 0) {
    const partHeader = `Auto-Transcript (part ${chunks.length + 1})\nGenerated by AssemblyAI\n\n`;
    const available = BOX_COMMENT_LIMIT - partHeader.length;
    if (remaining.length <= available) { chunks.push(partHeader + remaining); break; }
    let cutAt = available;
    const dot = remaining.lastIndexOf('. ', cutAt);
    if (dot > available * 0.6) { cutAt = dot + 2; } else { const sp = remaining.lastIndexOf(' ', cutAt); if (sp > 0) cutAt = sp; }
    chunks.push(partHeader + remaining.substring(0, cutAt).trimEnd());
    remaining = remaining.substring(cutAt).trimStart();
  }
  return chunks.map((c, i) => c.replace(`(part ${i + 1})`, `(part ${i + 1} of ${chunks.length})`));
}

function extractAudio(downloadUrl, tag) {
  const tempPath = path.join(os.tmpdir(), `bt_audio_${Date.now()}.mp3`);
  console.log(`${tag} Extracting audio via ffmpeg -> ${path.basename(tempPath)}`);
  return new Promise((resolve, reject) => {
    const proc = spawn(FFMPEG_PATH, ['-i', downloadUrl, '-vn', '-acodec', 'libmp3lame', '-ac', '1', '-ab', '64k', '-y', tempPath]);
    proc.stderr.on('data', () => {});
    proc.on('close', code => {
      if (code === 0) {
        const sizeMB = (fs.statSync(tempPath).size / 1024 / 1024).toFixed(1);
        console.log(`${tag} Audio extracted: ${sizeMB} MB`);
        resolve(tempPath);
      } else {
        reject(new Error(`ffmpeg exited with code ${code}`));
      }
    });
    proc.on('error', err => reject(new Error(`ffmpeg not found: ${err.message}`)));
  });
}

function handleTranscriptResult(transcript) {
  if (transcript.status === 'error') {
    if (transcript.error && transcript.error.includes('no spoken audio')) return null;
    throw new Error(`AssemblyAI error: ${transcript.error}`);
  }
  return transcript.text;
}

async function main() {
  const fileId = process.argv[2];
  if (!fileId) {
    console.error('Usage: node trigger.js <fileId> [fileName]');
    process.exit(1);
  }

  // Fetch file metadata from Box if name not provided
  let fileName = process.argv[3];
  let fileSize = 0;
  if (!fileName) {
    console.log('Fetching file info from Box...');
    const meta = await axios.get(`${BOX_API}/files/${fileId}`, { headers: boxHeaders() });
    fileName = meta.data.name;
    fileSize = meta.data.size;
    console.log(`File: ${fileName} | Size: ${(fileSize / 1024 / 1024 / 1024).toFixed(2)} GB`);
  }

  const tag = `[${fileName}]`;

  console.log(`${tag} Getting Box download URL...`);
  const downloadUrl = await getBoxDownloadUrl(fileId);

  let transcriptText;
  if (fileSize > FFMPEG_THRESHOLD_BYTES) {
    const sizeGB = (fileSize / 1024 / 1024 / 1024).toFixed(1);
    console.log(`${tag} Large file (${sizeGB} GB) — extracting audio first...`);
    let audioPath;
    try {
      audioPath = await extractAudio(downloadUrl, tag);
      console.log(`${tag} Uploading audio to AssemblyAI...`);
      const buffer = fs.readFileSync(audioPath);
      const uploadUrl = await aai.files.upload(buffer);
      console.log(`${tag} Transcription started — waiting for result...`);
      const transcript = await aai.transcripts.transcribe({ audio_url: uploadUrl, speech_models: ['universal-2'] });
      transcriptText = handleTranscriptResult(transcript);
    } finally {
      if (audioPath && fs.existsSync(audioPath)) { fs.unlinkSync(audioPath); console.log(`${tag} Temp audio file removed.`); }
    }
  } else {
    console.log(`${tag} Transcription started — waiting for result...`);
    const transcript = await aai.transcripts.transcribe({ audio_url: downloadUrl, speech_models: ['universal-2'] });
    transcriptText = handleTranscriptResult(transcript);
  }

  if (!transcriptText) { console.log(`${tag} No spoken audio detected.`); return; }
  console.log(`${tag} Transcript ready (${transcriptText.length} chars)`);

  const chunks = buildCommentChunks(transcriptText);
  console.log(`${tag} Posting ${chunks.length} comment(s) to Box...`);
  for (const chunk of chunks) { await postBoxComment(fileId, chunk); }
  console.log(`${tag} Done.`);
}

main().catch(err => {
  console.error('Failed:', err.response ? JSON.stringify(err.response.data, null, 2) : err.message);
  process.exit(1);
});
